language: python

python:
    - "2.7"

addons:
    apt:
        packages:
            - libopenmpi-dev
            - openmpi-bin
            - gfortran

install:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt
    - python setup.py install
    - pip install coveralls

# Tests are inside modules (doctest)
script:
    #- ./coverage_and_test.sh
    - coverage run --source=s4cmb s4cmb/*.py
    - python examples/simple_app.py -inifile examples/simple_parameters.ini -tag 'test'

after_success:
    coveralls
